<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.leo.ad</groupId>
        <artifactId>co-driver-statistics</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>co-driver-statistics-services</artifactId>
    <packaging>pom</packaging>

    <name>co-driver-statistics-services</name>
    <modules>
        <module>co-driver-statistics-service-common</module>
        <module>co-driver-statistics-service-dim</module>
        <module>co-driver-statistics-service-dwd</module>
        <module>co-driver-statistics-service-dws</module>
        <module>co-driver-statistics-service-ads</module>
        <module>co-driver-statistics-service-clean</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
        <dependency>
            <groupId>com.leo.ad</groupId>
            <artifactId>mysql-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.leo.ad</groupId>
            <artifactId>redis-spring-boot-starter</artifactId>
        </dependency>
    </dependencies>
</project>
