<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.leo.ad</groupId>
    <artifactId>co-driver</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>co-driver</name>
    <description>数据同一处理应用</description>
    <modules>
        <module>co-driver-spring-boot-starters</module>
        <module>co-driver-services</module>
        <module>co-driver-start</module>
        <module>co-driver-web</module>
        <module>co-driver-common</module>
    </modules>
    <properties>
        <revision>1.0</revision>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <spring-boot.version>3.0.2</spring-boot.version>
        <spring-cloud.version>2023.0.2</spring-cloud.version>
        <mysql.version>8.4.0</mysql.version>
        <druid.version>1.2.23</druid.version>
        <mybatisplus.version>3.5.6</mybatisplus.version>
        <lombok.version>1.18.22</lombok.version>
        <dynamic.datasource.version>4.3.0</dynamic.datasource.version>
        <redisson.version>3.30.0</redisson.version>
        <knife4j.version>4.5.0</knife4j.version>
        <fastjson2.version>2.0.50</fastjson2.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            <!-- 自定义 web -->
            <dependency>
                <groupId>com.leo.ad</groupId>
                <artifactId>co-driver-web</artifactId>
                <version>${revision}</version>
            </dependency>
            <!-- 自定义 service -->
            <dependency>
                <groupId>com.leo.ad</groupId>
                <artifactId>co-driver-common</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.leo.ad</groupId>
                <artifactId>co-driver-service-common</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.leo.ad</groupId>
                <artifactId>co-driver-service-dim</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.leo.ad</groupId>
                <artifactId>co-driver-service-dwd</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.leo.ad</groupId>
                <artifactId>co-driver-service-dws</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.leo.ad</groupId>
                <artifactId>co-driver-service-ads</artifactId>
                <version>${revision}</version>
            </dependency>
            <!-- 自定义 starter -->
            <dependency>
                <groupId>com.leo.ad</groupId>
                <artifactId>mysql-spring-boot-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.leo.ad</groupId>
                <artifactId>swagger-spring-boot-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.leo.ad</groupId>
                <artifactId>redis-spring-boot-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <dependency>
                <groupId>com.leo.ad</groupId>
                <artifactId>rabbitmq-spring-boot-starter</artifactId>
                <version>${revision}</version>
            </dependency>
            <!-- 第三方 -->
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-boot-starter</artifactId>
                <version>${mybatisplus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>dynamic-datasource-spring-boot3-starter</artifactId>
                <version>${dynamic.datasource.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-3-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>

            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>${mysql.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.xiaoymin</groupId>
                <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
                <version>${knife4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.redisson</groupId>
                <artifactId>redisson-spring-boot-starter</artifactId>
                <version>${redisson.version}</version>
            </dependency>
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson2.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <filesets>
                        <fileset>
                            <directory>${basedir}/logs</directory>
                        </fileset>
                    </filesets>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
