server:
  port: 8080

spring:
  application:
    name: co-driver
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  #  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.leo.ad.codriver.*.entity
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'

# 异步线程配置
async:
  executor:
    thread:
      # 配置核心线程数
      core_pool_size: 10
      # 配置最大线程数
      max_pool_size: 20
      # 配置队列大小
      queue_capacity: 99999
      # 配置线程池中的线程的名称前缀
      name:
        prefix: async-service-



logging:
  config: classpath:logback-spring.xml
  
