<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.leo.ad</groupId>
        <artifactId>co-driver-services</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>co-driver-service-dws</artifactId>
    <packaging>jar</packaging>

    <name>co-driver-service-dws</name>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.leo.ad</groupId>
            <artifactId>co-driver-service-common</artifactId>
        </dependency>
    </dependencies>
</project>
