<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>seatunnel-monitor</artifactId>
    <version>${revision}</version>
    <name>seatunnel-monitor</name>
    <packaging>jar</packaging>
    <parent>
        <groupId>com.leo.ad</groupId>
        <artifactId>co-driver-parent</artifactId>
        <version>1.0.3</version>
        <relativePath>../co-driver-parent</relativePath>
    </parent>


    <properties>
        <revision>1.0</revision>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.leo.ad</groupId>
            <artifactId>web-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.leo.ad</groupId>
            <artifactId>mysql-spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <!-- Spring Boot Maven 插件 -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <version>3.3.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>repackage</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
