server:
  port: 8081

spring:
  application:
    name: co-driver-monitor
  profiles:
    active: dev
  boot:
    admin:
      ui:
        title: ${spring.application.name}
        brand: "<img src=\"assets/img/icon-spring-boot-admin.svg\"><span>Co-Driver Monitor</span>"
      notify:
        dingtalk:
          enabled: false
          webhook-url: https://oapi.dingtalk.com/robot/send?access_token=72bd208edd3c1f9ad17a27ec660eb3e6a924a6a641df12e55bf51d312f0b1be6
          secret: SECe324d8b61d310b59fb8fe9294bb43a30faceac3b4c2ca23b6f2eb6813e8ce0b5
          ignore-changes:
            - "*:UP"
            - "UNKNOWN:DOWN"
          message: "服务状态发生变化：\n服务名称：#{instance.registration.name}\n服务状态：#{lastStatus} > #{event.statusInfo.status}\n服务实例：#{event.instance.value}\n服务实例地址：#{instance.registration.serviceUrl}"

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


logging:
  config: classpath:logback-spring.xml
  level:
    root: warn

