spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.31.45.176:8848
        namespace: public
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: mysql
      strict: false
      datasource:
        mysql:
          username: seatunnel
          password: seatunnelMysql
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.31.36.29:3306/analysis_data?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
          druid:
            initial-size: 10
            min-idle: 10
            max-active: 500
            max-wait: 60000
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 30000
            validation-query: select 'x'
            max-pool-prepared-statement-per-connection-size: 20
            filters: config,stat
  redis:
    redisson:
      file: classpath:redisson-prod.yml
  data:
    redis:
      sentinel:
        master: redis1
        nodes:
          - 172.31.41.156:16379
          - 172.31.46.109:16379
          - 172.31.41.23:16379
      jedis:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接
      database: 1
  rabbitmq:
    listener:
      direct:
        auto-startup: ${co-driver.rabbitmq.enable}
      simple:
        auto-startup: ${co-driver.rabbitmq.enable}
### 生产环境需要开启 enable
co-driver:
  rabbitmq:
    enable: true
    host: mq1.ronoinfo.com
    port: 5672
    username: max
    password: XzP9ZYrchRvrnpeVGZ1LJBeeZwkVSBIPZ
    virtualHost: /maxhost
    listener:
      data_change_queue:
        enable: true
      ods_user_change_queue:
        enable: true
      ods_user_config_group_queue:
        enable: true

management:
  health:
    rabbit:
      enabled: ${co-driver.rabbitmq.enable}
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: on
